remember_window_size no
initial_window_width 1920
initial_window_height 1080
window_padding_width 0

font_family TempleOS
font_size 12.0

modify_font cell_width 90%
modify_font cell_height 105%

enable_audio_bell yes
hide_window_decorations yes
