set -g prefix C-X
unbind C-a
bind C-X send-prefix

# status bar background color
set -g status-style bg='#C0C0C0',fg=black

# active window status color
set -g window-status-current-style bg='#0000B3',fg=white,bold

# not active window status color
set -g window-status-style bg=black,fg=gray

# active pane border color
set -g pane-active-border-style fg='#C0C0C0'

# not active pane border color
set -g pane-border-style fg=gray

#set -g status off
